### PR TITLE
Add system and utils unit tests

### PR DESCRIPTION
**Pull request by marjanAlbouye**
This PR adds more tests for the following modules:

1- All the setter methods for reference values in `System` base class. Cases with `ReferenceUnitError` are being tested too.

2- `ScaleEpsilon` and `ScaleSigma` in utils actions.

3- `xml_to_gmso_ff` in ff_utils.

### CODE REVIEW

**Comment by chrisjonesBSU** [comment]
@marjanAlbouye While we're making some small changes to the reference units attributes and setters, what do you think about adding a check for the correct dimensions?

units have a `dimensions` parameter that return `(mass), (length)` the dimensions for energy is `(length)**2*(mass)/(time)**2`

For example, we should throw an error if someone tries setting `reference_length` to a unit that doesn't have dimensions of `(length)`

**Comment by marjanAlbouye** [comment]
@chrisjonesBSU 
I added some checks in `system.py` to make sure the reference units have correct dimensions. Unit tests have been added accordingly.

**Comment by marjanAlbouye** [comment]
ToDo for me: Move all the checks related to units and their dimensions to utils to avoid having duplicated code. Also, allow unit strings with `/` character such as "kcal/mol".

**Comment by marjanAlbouye** [comment]
> > ToDo for me: Move all the checks related to units and their dimensions to utils to avoid having duplicated code. Also, allow unit strings with `/` character such as "kcal/mol".
> 
> Do you want to do that in this PR, or merge this and make a separate PR that streamlines the reference unit setters?

I was planning to do it in this PR but this PR is getting big. I'll merge this one and start a new one.

**Pull request merged**
